// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func WizardBanner() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"wizard-banner\" class=\"fixed bottom-0 inset-x-0 z-40 bg-gradient-to-r from-accent to-primary text-white p-4 shadow-2xl\" data-wizard-banner><div class=\"max-w-6xl mx-auto grid grid-cols-[1fr_auto] grid-rows-[1fr_auto] gap-y-4 xl:flex xl:items-center xl:justify-between\"><div class=\"flex items-center space-x-4\"><div class=\"hidden sm:block\"><svg class=\"w-12 h-12 text-white/80\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z\"></path></svg></div><div><h3 class=\"font-bold text-lg sm:text-xl\">¿Necesitas ayuda planificando tu evento?</h3><p class=\"text-white/90 text-sm sm:text-base\">Usa nuestro Asistente para Creación de Eventos y obtén recomendaciones personalizadas</p></div></div><button class=\"row-start-2 col-span-full self-center justify-self-stretch px-6 py-2 bg-white text-accent font-bold rounded-lg hover:bg-gray-100 transition-colors shadow-lg\" hx-get=\"/wizard/selection\" hx-target=\"#wizard-modal\" hx-indicator=\"#wizard-modal-loading\" data-open-wizard data-click-handler-selector=\"open-wizard\">Usar Asistente</button> <button class=\"col-start-2 row-start-1 self-start p-2 text-white/80 hover:text-white transition-colors\" data-dismiss-wizard-banner data-click-handler-selector=\"dismiss-wizard-banner\"><svg class=\"w-6 h-6\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M6 18L18 6M6 6l12 12\"></path></svg></button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func WizardBannerScript() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<script>\n\t\tdocument.addEventListener('DOMContentLoaded', function() {\n\t\t\tconst banner = document.getElementById('wizard-banner');\n\t\t\tlet bannerDismissed = localStorage.getItem('wizardBannerDismissed') === 'true';\n\t\t\t\n\t\t\t// Show banner after 3 seconds if not dismissed\n\t\t\tif (!bannerDismissed) {\n\t\t\t\tsetTimeout(() => {\n\t\t\t\t\tif (banner) {\n\t\t\t\t\t\tbanner.classList.remove('translate-y-full');\n\t\t\t\t\t\tbanner.classList.add('translate-y-0');\n\t\t\t\t\t}\n\t\t\t\t}, 1000);\n\t\t\t} else {\n\t\t\t\t// Hide banner if previously dismissed\n\t\t\t\tif (banner) {\n\t\t\t\t\tbanner.classList.add('translate-y-full');\n\t\t\t\t}\n\t\t\t}\n\n            eventManager\n                .registerClick('dismiss-wizard-banner', function(e) {\n                    localStorage.setItem('wizardBannerDismissed', 'true');\n\n                    const banner = document.getElementById('wizard-banner');\n                    if (banner) {\n                        banner.classList.add('hidden');\n                    }\n                })\n\t\t\t\t.registerClick('open-wizard', function(e) {\n                    console.log(e)\n\t\t\t\t\tif (typeof showWizardModal === 'function') {\n\t\t\t\t\t\tshowWizardModal();\n\t\t\t\t\t}\n\t\t\t\t});\n\t\t});\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
