// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package dashboard

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"github.com/vladwithcode/salon_catalog/internal/db"
)

type CategoryImagesTabUpdateData struct {
	HeaderImgFilename  string
	HeaderImgID        string
	DisplayImgFilename string
	DisplayImgID       string
}

func CategoryImagesTab(category *db.Category, updateData *CategoryImagesTabUpdateData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"h-full w-full overflow-auto space-y-4 p-4\"><!-- Header Image Section --><div class=\"space-y-2\"><h4 class=\"text-sm font-medium text-gray-700\">Imagen de Cabecera</h4><div id=\"headerImgSection\" class=\"space-y-2\"><div class=\"flex gap-2\"><button id=\"categories-modal-images-select-header\" class=\"px-3 py-1 text-sm border border-gray-300 text-gray-700 rounded-sm hover:bg-gray-50 transition-colors\" hx-get=\"/imagenes/selector\" hx-vals=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs((&ImageSelectorConfig{
			Mode:           "single",
			UpdateEndpoint: fmt.Sprintf("/panel/categorias/%s/header_img", category.ID),
			Title:          "Seleccionar la imagen de cabecera para " + category.Name,
			MaxSelection:   1,
			SelectedIds:    []string{category.HeaderImgID},
			SuccessTarget:  "#headerImgSection",
		}).ToJSONString())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/dashboard/category_images_tab.templ`, Line: 33, Col: 41}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" hx-target=\"body\" hx-swap=\"beforeend\" hx-indicator=\"#global-loading-indicator\">Seleccionar</button> <button id=\"categories-modal-images-unset-header\" class=\"px-3 py-1 text-sm border border-red-300 text-red-700 rounded-sm hover:bg-red-50 transition-colors\" hx-delete=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("/panel/categorias/%s/header_img", category.ID))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/dashboard/category_images_tab.templ`, Line: 43, Col: 77}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" hx-target=\"#headerImgSection\" hx-indicator=\"#global-loading-indicator\" hx-confirm=\"¿Seguro que deseas eliminar la imagen de cabecera?\">Quitar</button></div><div class=\"flex space-x-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if (updateData != nil && updateData.HeaderImgFilename != "") || category.HeaderImg != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"relative w-16 h-16 rounded-md overflow-hidden border border-gray-200\"><button type=\"button\" class=\"w-full h-full\" data-click-handler-selector=\"category-modal-images-btn\"><img src=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("/static/uploads/%s",
				func() string {
					if updateData != nil && updateData.HeaderImgFilename != "" {
						return updateData.HeaderImgFilename
					}
					return category.HeaderImg
				}()))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/dashboard/category_images_tab.templ`, Line: 62, Col: 15}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" alt=\"Header\" class=\"w-full h-full object-cover\"></button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div></div></div><!-- Display Image Section --><div class=\"space-y-2\"><h4 class=\"text-sm font-medium text-gray-700\">Imagen de Visualización</h4><div id=\"displayImgSection\" class=\"space-y-2\"><div class=\"flex gap-2\"><button id=\"categories-modal-images-select-display\" class=\"px-3 py-1 text-sm border border-gray-300 text-gray-700 rounded-sm hover:bg-gray-50 transition-colors\" hx-get=\"/imagenes/selector\" hx-vals=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf(`{
								"mode": "single",
								"updateEndpoint": "/panel/categorias/%s/display_img",
								"maxSelection": "1",
								"successTarget": "#displayImgSection"
							}`, category.ID))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/dashboard/category_images_tab.templ`, Line: 86, Col: 23}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" hx-target=\"body\" hx-swap=\"beforeend\" hx-indicator=\"#global-loading-indicator\">Seleccionar</button> <button id=\"categories-modal-images-unset-display\" class=\"px-3 py-1 text-sm border border-red-300 text-red-700 rounded-sm hover:bg-red-50 transition-colors\" hx-delete=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("/panel/categorias/%s/display_img", category.ID))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/dashboard/category_images_tab.templ`, Line: 96, Col: 78}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" hx-target=\"#displayImgSection\" hx-indicator=\"#global-loading-indicator\" hx-confirm=\"¿Seguro que deseas eliminar la imagen de visualización?\">Quitar</button></div><div class=\"flex space-x-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if (updateData != nil && updateData.DisplayImgFilename != "") || category.DisplayImg != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<div class=\"relative w-16 h-16 rounded-md overflow-hidden border border-gray-200\"><button type=\"button\" class=\"w-full h-full\" data-click-handler-selector=\"category-modal-images-btn\"><img src=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("/static/uploads/%s",
				func() string {
					if updateData != nil && updateData.DisplayImgFilename != "" {
						return updateData.DisplayImgFilename
					}
					return category.DisplayImg
				}()))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/components/dashboard/category_images_tab.templ`, Line: 115, Col: 15}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\" alt=\"Display\" class=\"w-full h-full object-cover\"></button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
