// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.920
package dashboard

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/vladwithcode/salon_catalog/internal/templates/components"

func QuickActions() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script>\n    document.addEventListener('DOMContentLoaded', function () {\n        eventManager.registerClick('quick-actions-toggle', (e) => {\n            const list = document.getElementById('quick-actions-list');\n            const isOpen = list.dataset.quickActionsOpen === 'true';\n            const duration = 0.15;\n            const easing = 'power2.out';\n\n            if (isOpen) {\n                gsap.to(list, {\n                    height: 0,\n                    duration,\n                    ease: easing,\n                });\n                gsap.to('[data-quick-toggle-chevron]', {\n                    rotate: '-90deg',\n                    duration,\n                    ease: easing,\n                }, \"<\");\n                list.dataset.quickActionsOpen = 'false';\n            } else {\n                gsap.to(list, {\n                    height: 'auto',\n                    duration,\n                    ease: easing,\n                });\n                gsap.to('[data-quick-toggle-chevron]', {\n                    rotate: 0,\n                    duration,\n                    ease: easing,\n                }, \"<\");\n                list.dataset.quickActionsOpen = 'true';\n            }\n        });\n    });\n</script><div class=\"px-4 \"><button id=\"quick-actions-toggle\" class=\"flex w-full justify-between py-2 focus:outline-accent text-gray-700\" data-click-handler-selector=\"quick-actions-toggle\"><h3 class=\"text-lg font-semibold\">Acciones Rápidas</h3>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.ChevronIcon("w-6", templ.Attributes{"data-quick-toggle-chevron": true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</button><div class=\"h-px border-t border-gray-200 pb-2\"></div><div id=\"quick-actions-list\" class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 overflow-hidden\" data-quick-actions-open=\"true\"><a href=\"/panel/productos/nuevo\" class=\"flex items-center p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors\"><div class=\"w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center mr-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.PlusIcon("w-5 h-5 text-blue-600", nil).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div><p class=\"font-medium text-gray-900\">Nuevo producto</p><p class=\"text-sm text-gray-600\">Crear nuevo producto</p></div></a> <a href=\"/panel/asistente/nuevo\" class=\"flex items-center p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors\"><div class=\"w-10 h-10 bg-yellow-100 rounded-lg flex items-center justify-center mr-4\"><svg class=\"w-5 h-5\"><use href=\"/static/assets/wizard.svg#wizard\"></use></svg></div><div><p class=\"font-medium text-gray-900\">Nuevo asistente</p><p class=\"text-sm text-gray-600\">Crear nuevo asistente de planeación</p></div></a> <a href=\"/panel/mensajes\" class=\"flex items-center p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors\"><div class=\"w-10 h-10 bg-green-100 rounded-lg flex items-center justify-center mr-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.EmailIcon("w-5 h-5 text-green-600", nil).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><div><p class=\"font-medium text-gray-900\">Ver mensajes</p><p class=\"text-sm text-gray-600\">Solicitudes de contacto</p></div></a> <a href=\"/panel/reportes\" class=\"flex items-center p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors\"><div class=\"w-10 h-10 bg-purple-100 rounded-lg flex items-center justify-center mr-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.GraphIcon("w-5 h-5 text-purple-600", nil).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div><p class=\"font-medium text-gray-900\">Ver reportes</p><p class=\"text-sm text-gray-600\">Panel de analíticas</p></div></a></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
